import platform
from os import environ
from pathlib import Path


class Directory:
    """This is a very simple class meant to centralize the definition of the "root path" related to 
    alyx's connector configuration (for cache, server & user config and basically anything that may 
    need to persist on disk), on each different operating system supported.
    """
    directory_name: str | Path # directory

    @property
    def root_path(self) -> Path:
        # windows
        if platform == "win32" or platform == "cygwin":
            return Path(environ["LOCALAPPDATA"]) / self.directory_name
        # linux / mac / else
        else:
            return Path.home() / self.directory_name


class LocalData(Directory):
    """Unused class (for now) meant to be used for obtaining the location of where the data 
    locations obtained through alyx's data structure, should point to.
    """
    directory_name = "Downloads/alyx_data"

class RequestsCache(Directory):
    """Class used for locating where the cache generated by alyx's requests, should be stored.
    """
    directory_name = ".alyx_connector/requests_cache"