site_name: Alyx-Local-Connector
site_url: https://josttim.github.io/alyx-local-connector/
docs_dir: "./documentation_files"
repo_url: https://github.com/JostTim/alyx-local-connector
repo_name: Alyx-Local-Connector on GitHub

theme:
  name: material
  logo: "./.media/favicon.svg"
  favicon: "./.media/favicon.svg"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: cyan
      accent: purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: cyan
      accent: purple
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      accent: purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.link
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - content.tooltips
    - header.permalinks
    - toc.follow

markdown_extensions:
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append: ["abbreviations.md"]
      base_path: ["docs"]
      check_paths: True
      url_download: True
  - toc:
      permalink: true
  - tables
  - admonition

nav:
  - Home: "index.md"

exclude_docs: |
  !.assets/

extra_css:
  - .assets/stylesheets/extra.css
